### ISSUE TITLE
Get stuck when going into batch_dict = self.matcher(batch_dict).

### ISSUE THREAD

**Issue by yifanlu0227** [YuanYunshuang/FPV_RCNN#3]
Hi! When I try to run `tools/train_fusion_detector.py` with `cfg/fusion_pvrcnn_comap.py`, I find I fall in a dead loop in MatcherV3' s clustering method. 

cluster_indices.shape: torch.Size([1608])
ious.shape: torch.Size([1608, 1608])
`torch.where(ious[cur_idx] > 0.1)` returns all empty tensor in the end, like `(tensor([], device='cuda:0', dtype=torch.int64),)`. 

Then I simply replace MatcherV3 with MatcherV2, I meet another error: 
```
File "/GPFS/data/yifanlu/FPV_RCNN/losses/smooth_l1_loss.py", line 55, in forward
    anchorwise_smooth_l1norm *= weights.unsqueeze(-1) # pos_anchors multiply the weight: 1/num_pos_anchor in each sample
...
RuntimeError: Function 'MulBackward0' returned nan values in its 0th output.
```

There are some other questions I look forward to your answers:

I find the pretrained model cia_ssd.pth you provide don't come in handy. Where to load it?

If I do not have the class labels of points, can I train the SemSeg network? Since I want to apply this method in other dataset.

**Comment by YuanYunshuang** [comment]
Hi, you might meet this error because you train the whole model from scratch. In the beginning, you should either train the cia-ssd part or load the checkpoint provided. Otherwise, the second stage would just waste time on learning only from negative samples. That is why the first stage is first trained. I updated the code as well as the Readme file so that it is more clear on how the checkpoint should be loaded.

For the second question, you can not train the semseg head if you do not have the class labels. But if you do not have this label in your dataset, I recommend you train first on comap,  freeze the parameters for semseg head and only train the other part of the model. This might give you some classification results but might not perform very well since there is still a domain gap. However, if do not need to do the localization error correction in you dataset, you do not need the semseg at all.

I hope this helps.

**Comment by yifanlu0227** [comment]
Thanks!
